# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DHT_interface.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(799, 820)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/temp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.temperatureLCD = QtWidgets.QLCDNumber(Dialog)
        self.temperatureLCD.setGeometry(QtCore.QRect(30, 200, 181, 111))
        self.temperatureLCD.setObjectName("temperatureLCD")
        self.humidityLCD = QtWidgets.QLCDNumber(Dialog)
        self.humidityLCD.setGeometry(QtCore.QRect(570, 200, 181, 111))
        self.humidityLCD.setObjectName("humidityLCD")
        self.requestDataButton = QtWidgets.QPushButton(Dialog)
        self.requestDataButton.setGeometry(QtCore.QRect(300, 250, 191, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requestDataButton.sizePolicy().hasHeightForWidth())
        self.requestDataButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.requestDataButton.setFont(font)
        self.requestDataButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.requestDataButton.setAutoDefault(True)
        self.requestDataButton.setDefault(False)
        self.requestDataButton.setFlat(False)
        self.requestDataButton.setObjectName("requestDataButton")
        self.lastRequestTime = QtWidgets.QLabel(Dialog)
        self.lastRequestTime.setEnabled(True)
        self.lastRequestTime.setGeometry(QtCore.QRect(250, 170, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lastRequestTime.setFont(font)
        self.lastRequestTime.setToolTip("")
        self.lastRequestTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lastRequestTime.setAutoFillBackground(False)
        self.lastRequestTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lastRequestTime.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lastRequestTime.setLineWidth(1)
        self.lastRequestTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lastRequestTime.setIndent(-1)
        self.lastRequestTime.setObjectName("lastRequestTime")
        self.temperatureIconLabel = QtWidgets.QLabel(Dialog)
        self.temperatureIconLabel.setGeometry(QtCore.QRect(60, 0, 101, 141))
        self.temperatureIconLabel.setText("")
        self.temperatureIconLabel.setPixmap(QtGui.QPixmap("Resources/temp1.png"))
        self.temperatureIconLabel.setObjectName("temperatureIconLabel")
        self.humidityIconLabel = QtWidgets.QLabel(Dialog)
        self.humidityIconLabel.setGeometry(QtCore.QRect(610, 0, 141, 151))
        self.humidityIconLabel.setText("")
        self.humidityIconLabel.setPixmap(QtGui.QPixmap("Resources/hum.png"))
        self.humidityIconLabel.setObjectName("humidityIconLabel")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(240, 20, 20, 651))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(530, 20, 20, 651))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.sensorStatus = QtWidgets.QLabel(Dialog)
        self.sensorStatus.setGeometry(QtCore.QRect(300, 80, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sensorStatus.setFont(font)
        self.sensorStatus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sensorStatus.setStyleSheet("QLabel { background-color : red; color : white; }")
        self.sensorStatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensorStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.sensorStatus.setObjectName("sensorStatus")
        self.stopTimerButton = QtWidgets.QPushButton(Dialog)
        self.stopTimerButton.setGeometry(QtCore.QRect(410, 590, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopTimerButton.setFont(font)
        self.stopTimerButton.setObjectName("stopTimerButton")
        self.startTimerButton = QtWidgets.QPushButton(Dialog)
        self.startTimerButton.setGeometry(QtCore.QRect(280, 590, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.startTimerButton.setFont(font)
        self.startTimerButton.setObjectName("startTimerButton")
        self.timerResolutionSpinBox = QtWidgets.QSpinBox(Dialog)
        self.timerResolutionSpinBox.setGeometry(QtCore.QRect(420, 530, 91, 41))
        self.timerResolutionSpinBox.setMinimum(1)
        self.timerResolutionSpinBox.setMaximum(10)
        self.timerResolutionSpinBox.setObjectName("timerResolutionSpinBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 530, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CtempButton = QtWidgets.QPushButton(Dialog)
        self.CtempButton.setGeometry(QtCore.QRect(30, 150, 51, 51))
        self.CtempButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Downloads/celsius.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.CtempButton.setIcon(icon1)
        self.CtempButton.setIconSize(QtCore.QSize(100, 100))
        self.CtempButton.setObjectName("CtempButton")
        self.FtempButton = QtWidgets.QPushButton(Dialog)
        self.FtempButton.setGeometry(QtCore.QRect(80, 150, 51, 51))
        self.FtempButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/farh.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.FtempButton.setIcon(icon2)
        self.FtempButton.setIconSize(QtCore.QSize(100, 100))
        self.FtempButton.setObjectName("FtempButton")
        self.humUnitThresholdDisplaySlider = QtWidgets.QSlider(Dialog)
        self.humUnitThresholdDisplaySlider.setGeometry(QtCore.QRect(580, 370, 160, 26))
        self.humUnitThresholdDisplaySlider.setSliderPosition(40)
        self.humUnitThresholdDisplaySlider.setOrientation(QtCore.Qt.Horizontal)
        self.humUnitThresholdDisplaySlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.humUnitThresholdDisplaySlider.setTickInterval(10)
        self.humUnitThresholdDisplaySlider.setObjectName("humUnitThresholdDisplaySlider")
        self.tempUnitThresholdDisplaySlider = QtWidgets.QSlider(Dialog)
        self.tempUnitThresholdDisplaySlider.setGeometry(QtCore.QRect(60, 370, 160, 26))
        self.tempUnitThresholdDisplaySlider.setSingleStep(1)
        self.tempUnitThresholdDisplaySlider.setProperty("value", 20)
        self.tempUnitThresholdDisplaySlider.setSliderPosition(20)
        self.tempUnitThresholdDisplaySlider.setOrientation(QtCore.Qt.Horizontal)
        self.tempUnitThresholdDisplaySlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.tempUnitThresholdDisplaySlider.setTickInterval(10)
        self.tempUnitThresholdDisplaySlider.setObjectName("tempUnitThresholdDisplaySlider")
        self.humtemp_disabledButton = QtWidgets.QPushButton(Dialog)
        self.humtemp_disabledButton.setEnabled(True)
        self.humtemp_disabledButton.setGeometry(QtCore.QRect(570, 150, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.humtemp_disabledButton.setFont(font)
        self.humtemp_disabledButton.setIconSize(QtCore.QSize(100, 100))
        self.humtemp_disabledButton.setObjectName("humtemp_disabledButton")
        self.tempValueThresholdDisplayLabel = QtWidgets.QLabel(Dialog)
        self.tempValueThresholdDisplayLabel.setGeometry(QtCore.QRect(40, 410, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.tempValueThresholdDisplayLabel.setFont(font)
        self.tempValueThresholdDisplayLabel.setObjectName("tempValueThresholdDisplayLabel")
        self.tempUnitThresholdDisplayLabel = QtWidgets.QLabel(Dialog)
        self.tempUnitThresholdDisplayLabel.setGeometry(QtCore.QRect(90, 410, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.tempUnitThresholdDisplayLabel.setFont(font)
        self.tempUnitThresholdDisplayLabel.setObjectName("tempUnitThresholdDisplayLabel")
        self.humValueThresholdDisplayLabel = QtWidgets.QLabel(Dialog)
        self.humValueThresholdDisplayLabel.setGeometry(QtCore.QRect(580, 410, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.humValueThresholdDisplayLabel.setFont(font)
        self.humValueThresholdDisplayLabel.setObjectName("humValueThresholdDisplayLabel")
        self.hmuUnitThresholdDisplayLabel = QtWidgets.QLabel(Dialog)
        self.hmuUnitThresholdDisplayLabel.setGeometry(QtCore.QRect(630, 410, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.hmuUnitThresholdDisplayLabel.setFont(font)
        self.hmuUnitThresholdDisplayLabel.setObjectName("hmuUnitThresholdDisplayLabel")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 330, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(580, 330, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tempThresholdAlarm = QtWidgets.QLabel(Dialog)
        self.tempThresholdAlarm.setGeometry(QtCore.QRect(80, 480, 91, 101))
        self.tempThresholdAlarm.setStyleSheet("")
        self.tempThresholdAlarm.setText("")
        self.tempThresholdAlarm.setPixmap(QtGui.QPixmap("Resources/alarm.png"))
        self.tempThresholdAlarm.setScaledContents(True)
        self.tempThresholdAlarm.setObjectName("tempThresholdAlarm")
        self.humThresholdAlarm = QtWidgets.QLabel(Dialog)
        self.humThresholdAlarm.setGeometry(QtCore.QRect(630, 470, 91, 101))
        self.humThresholdAlarm.setStyleSheet("")
        self.humThresholdAlarm.setText("")
        self.humThresholdAlarm.setPixmap(QtGui.QPixmap("Resources/alarm.png"))
        self.humThresholdAlarm.setScaledContents(True)
        self.humThresholdAlarm.setObjectName("humThresholdAlarm")
        self.realtimeGraphTimerCheckbox = QtWidgets.QCheckBox(Dialog)
        self.realtimeGraphTimerCheckbox.setGeometry(QtCore.QRect(300, 460, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.realtimeGraphTimerCheckbox.setFont(font)
        self.realtimeGraphTimerCheckbox.setObjectName("realtimeGraphTimerCheckbox")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(260, 440, 271, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.todaysDateLabel = QtWidgets.QLabel(Dialog)
        self.todaysDateLabel.setGeometry(QtCore.QRect(280, 20, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.todaysDateLabel.setFont(font)
        self.todaysDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.todaysDateLabel.setObjectName("todaysDateLabel")
        self.staticGraphButton = QtWidgets.QPushButton(Dialog)
        self.staticGraphButton.setGeometry(QtCore.QRect(10, 680, 621, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.staticGraphButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.staticGraphButton.setIcon(icon3)
        self.staticGraphButton.setIconSize(QtCore.QSize(150, 150))
        self.staticGraphButton.setObjectName("staticGraphButton")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(260, 660, 271, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.clearReadingsButton = QtWidgets.QPushButton(Dialog)
        self.clearReadingsButton.setGeometry(QtCore.QRect(640, 680, 151, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.clearReadingsButton.setFont(font)
        self.clearReadingsButton.setObjectName("clearReadingsButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(520, 790, 271, 21))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EID Thermostat"))
        self.requestDataButton.setText(_translate("Dialog", "Request Data"))
        self.lastRequestTime.setText(_translate("Dialog", "Last Request Time"))
        self.sensorStatus.setText(_translate("Dialog", "Sensor Disconnected"))
        self.stopTimerButton.setText(_translate("Dialog", "Stop Timer"))
        self.startTimerButton.setText(_translate("Dialog", "Start Timer"))
        self.label.setText(_translate("Dialog", "Timer Resolution"))
        self.humtemp_disabledButton.setText(_translate("Dialog", "%"))
        self.tempValueThresholdDisplayLabel.setText(_translate("Dialog", "20"))
        self.tempUnitThresholdDisplayLabel.setText(_translate("Dialog", "C"))
        self.humValueThresholdDisplayLabel.setText(_translate("Dialog", "40"))
        self.hmuUnitThresholdDisplayLabel.setText(_translate("Dialog", "%"))
        self.label_2.setText(_translate("Dialog", "Threshold"))
        self.label_3.setText(_translate("Dialog", "Threshold"))
        self.realtimeGraphTimerCheckbox.setText(_translate("Dialog", "Real Time Graph"))
        self.todaysDateLabel.setText(_translate("Dialog", "Todays Date"))
        self.staticGraphButton.setText(_translate("Dialog", "Stored Readings Graph"))
        self.clearReadingsButton.setText(_translate("Dialog", "Clear Readings"))
        self.label_4.setText(_translate("Dialog", "Designed & Developed - Gunj Manseta"))

