# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(585, 774)
        self.req_data = QtWidgets.QPushButton(dialog)
        self.req_data.setGeometry(QtCore.QRect(40, 40, 141, 29))
        self.req_data.setObjectName("req_data")
        self.c_to_f = QtWidgets.QPushButton(dialog)
        self.c_to_f.setGeometry(QtCore.QRect(450, 40, 91, 29))
        self.c_to_f.setObjectName("c_to_f")
        self.gen_graph = QtWidgets.QPushButton(dialog)
        self.gen_graph.setGeometry(QtCore.QRect(160, 540, 191, 29))
        self.gen_graph.setObjectName("gen_graph")
        self.display_values = QtWidgets.QTextEdit(dialog)
        self.display_values.setGeometry(QtCore.QRect(10, 100, 551, 411))
        self.display_values.setObjectName("display_values")
        self.clear_data = QtWidgets.QPushButton(dialog)
        self.clear_data.setGeometry(QtCore.QRect(240, 40, 161, 29))
        self.clear_data.setObjectName("clear_data")
        self.executeProtocolCompButton = QtWidgets.QPushButton(dialog)
        self.executeProtocolCompButton.setGeometry(QtCore.QRect(10, 620, 111, 121))
        font = QtGui.QFont()
        font.setKerning(True)
        self.executeProtocolCompButton.setFont(font)
        self.executeProtocolCompButton.setObjectName("executeProtocolCompButton")
        self.comparisionTable = QtWidgets.QTableWidget(dialog)
        self.comparisionTable.setGeometry(QtCore.QRect(140, 620, 411, 131))
        self.comparisionTable.setRowCount(4)
        self.comparisionTable.setColumnCount(4)
        self.comparisionTable.setObjectName("comparisionTable")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.comparisionTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.comparisionTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.comparisionTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.comparisionTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.comparisionTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.comparisionTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.comparisionTable.setItem(3, 0, item)
        self.comparisionTable.horizontalHeader().setVisible(False)
        self.comparisionTable.horizontalHeader().setHighlightSections(False)
        self.comparisionTable.verticalHeader().setVisible(False)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.req_data.setText(_translate("dialog", "REQUEST DATA"))
        self.c_to_f.setText(_translate("dialog", "C/F"))
        self.gen_graph.setText(_translate("dialog", "GENERATE GRAPH"))
        self.clear_data.setText(_translate("dialog", "CLEAR DATA"))
        self.executeProtocolCompButton.setText(_translate("dialog", "Execute\n"
" Protocol\n"
" Tests"))
        __sortingEnabled = self.comparisionTable.isSortingEnabled()
        self.comparisionTable.setSortingEnabled(False)
        item = self.comparisionTable.item(0, 0)
        item.setText(_translate("dialog", "Protocol"))
        item = self.comparisionTable.item(0, 1)
        item.setText(_translate("dialog", "Start Time"))
        item = self.comparisionTable.item(0, 2)
        item.setText(_translate("dialog", "End Time"))
        item = self.comparisionTable.item(0, 3)
        item.setText(_translate("dialog", "Time"))
        item = self.comparisionTable.item(1, 0)
        item.setText(_translate("dialog", "MQTT"))
        item = self.comparisionTable.item(2, 0)
        item.setText(_translate("dialog", "Websockets"))
        item = self.comparisionTable.item(3, 0)
        item.setText(_translate("dialog", "CoAp"))
        self.comparisionTable.setSortingEnabled(__sortingEnabled)

